
title: Mastering SQL Window Functions
email: chauhanjugal4@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Discovering the potential of SQL window functions to generate meaningful insights

#github_username:  patdryburgh

# Build settings
markdown: kramdown

theme: jekyll-theme-minima
